name: Build and Test

on: [pull_request]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v4

    - name: Build
      run: |
        xcodebuild build -project RecipesTracker.xcodeproj -scheme RecipesTracker clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

    - name: Run tests
      run: |
        xcodebuild test -project RecipesTracker.xcodeproj -scheme RecipesTracker clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max'
